# mysql
spring:
  datasource:
    #MySQL配置
    driverClassName:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easyproject?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  # mybatis 映射文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.model
server:
  # vue占用8080
  port: 9000

#jwt配置
jwt:
  # 请求头
  tokenHeader: Authorization
  # 签名
  secret: tryasecret1234
  # 过期时间
  expiration: 1800
  # token头部
  tokenHead: "Bearer "